import { StyleSheet } from "react-native";
import Colors from "../constants/Colors";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		backgroundColor: Colors.beige,
		justifyContent: "center",
		padding: 20,
	},
	scrollView: {
		flex: 1,
		width: "100%",
	},
	button: {
		marginTop: 50,
		width: "50%",
		alignSelf: "center",
		marginBottom: 50,
		backgroundColor: Colors.orange,
	},
	title: {
		fontSize: 24,
		fontFamily: "OptimaRoman",
		fontWeight: "bold",
		marginBottom: 30,
		color: Colors.darkGreen,
	},
	itemsContainer: {
		gap: 10,
	},
	itemRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		padding: 15,
		backgroundColor: Colors.white,
		borderRadius: 15,
		borderWidth: 1,
		borderColor: "#dddddd",
	},
	changeRow: {
		flexDirection: "row",
		gap: 8,
	},
	changeName: {
		flex: 4,
		padding: 15,
		backgroundColor: Colors.white,
		borderRadius: 15,
		borderWidth: 1,
		borderColor: "#dddddd",
	},
	changePrice: {
		flex: 1,
		padding: 15,
		backgroundColor: Colors.white,
		borderRadius: 15,
		borderWidth: 1,
		borderColor: "#dddddd",
	},
	itemName: {
		fontFamily: "WorkSans",
		fontSize: 16,
		color: Colors.black,
		flex: 1,
	},
	itemPrice: {
		fontFamily: "WorkSans-Medium",
		fontSize: 16,
		color: Colors.orange,
	},
	subtotalContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		padding: 15,
		marginTop: 20,
		backgroundColor: Colors.white,
		borderRadius: 15,
		borderWidth: 1,
		borderColor: "#dddddd",
	},
	subtotalLabel: {
		fontFamily: "WorkSans-Medium",
		fontSize: 16,
		color: Colors.black,
	},
	subtotalAmount: {
		fontSize: 16,
		fontFamily: "WorkSans-SemiBold",
		color: Colors.orange,
	},
	deleteAction: {
		backgroundColor: "#ff5252",
		justifyContent: "center",
		alignItems: "center",
		width: 80,
		height: "100%",
		borderRadius: 15,
		marginLeft: 5,
	},
	modalOverlay: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	modalContainer: {
		width: 300,
		height: 200,
	},
	modalSurface: {
		width: "100%",
		padding: 20,
		borderRadius: 12,
		backgroundColor: "#ffffff",
		elevation: 5,
		borderWidth: 2,
		borderColor: "#b2ebf2",
	},
	modalTitle: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#00838f",
		marginBottom: 20,
		textAlign: "center",
	},
	modalInput: {
		backgroundColor: "#ffffff",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#b2ebf2",
		marginBottom: 15,
		padding: 12,
	},
	modalButton: {
		backgroundColor: "#00acc1",
		padding: 15,
		borderRadius: 8,
		alignItems: "center",
		marginTop: 10,
	},
	modalButtonText: {
		color: "#ffffff",
		fontSize: 16,
		fontWeight: "bold",
	},
	footer: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		height: 100,
		backgroundColor: "white",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
		paddingHorizontal: 20,
		borderTopWidth: 1,
		borderTopColor: "#e0e0e0",
		elevation: 8, // for Android shadow
		shadowColor: "#000", // for iOS shadow
		shadowOffset: {
			width: 0,
			height: -2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
	},
	footerButton: {
		width: 40,
		height: 40,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 15,
		backgroundColor: "#f5f5f5",
		borderColor: "#e0f7fa",
		borderWidth: 4,
	},
	footerIcon: {
		width: 24,
		height: 24,
		resizeMode: "contain",
	},
	continueButton: {
		width: 60,
		height: 60,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 30,
		backgroundColor: "#f5f5f5",
		borderColor: "#e0f7fa",
		borderWidth: 4,
	},
	continueIcon: {
		width: 30,
		height: 30,
		resizeMode: "contain",
	},
});
